### ISSUE TITLE
How to use grapesjs to Ruby on Rails 6 app?

### ISSUE THREAD

**Issue by Excellent-Developer** [artf/grapesjs#2466]
I am going to use this in Rails 6 app.
https://grapesjs.com/docs/getting-started.html#import-the-library
I developed under this guide.
But, It is not like a guide.
I think CSS is not working well.
My result
![image](https://user-images.githubusercontent.com/54437031/71345196-a070db80-259f-11ea-871d-fbfcc870b15a.png)
Guide result.
![image](https://user-images.githubusercontent.com/54437031/71345243-bb435000-259f-11ea-9a1c-942df002594c.png)

I will appreciate it if you kindly teach me how to use this on Rails 6.

**Comment by artf** [comment]
GrapesJS has nothing to do with your back-end stack and seems like you just didn't use the CSS in examples, eg:
```css
#gjs {
  border: 3px solid #444;
}

/* Reset some default styling */
.gjs-cv-canvas {
  top: 0;
  width: 100%;
  height: 100%;
}
```
