### ISSUE TITLE
[bug]: Style Manager has a giant + sign

### ISSUE THREAD

**Issue by eD572** [artf/grapesjs#2490]
Hi art, 
 there seems to be a problem with the Classes attribute in style manager, a Giant plus sign keeps displaying itself, whether I use it locally from my copy or on your demo.

Version: Latest as of this date
Browser: Mozilla
OS: Ubuntu 18.04
Bug: Giant + on style manager

 
![bug](https://user-images.githubusercontent.com/59544748/71788740-ffcef100-305f-11ea-85fe-040b5ddecfd0.png)

Hey art just an update, think it's a mozilla thing. Tested with brave, opera, chrome, duckduckgo and mozilla on my phone only mozilla shows the issue.

**Comment by senchden** [comment]
Can confirm on Firefox 72. Teseted with web page demo version 0.15.10. Several view icons have incorrect size: 
![image](https://user-images.githubusercontent.com/31250983/72080121-7a1ba180-32fc-11ea-9d9b-be64f4610a2c.png)

**Comment by artf** [comment]
Ok thanks for the report, I'll adjust them in the next release, for now, you can this CSS as a temporary fix:
```css
.gjs-clm-tag-status, 
.gjs-clm-tag-close {
    width: 12px;
    height: 12px;
}
.gjs-clm-tags-btn {
    width: 24px;
}
```
