### ISSUE TITLE
[Question] How to append style manager to custom panel

### ISSUE THREAD

**Issue by christianbalderrama** [artf/grapesjs#2687]
I would like to append the whole style manager module to a panel? I have been digging up the docs for the past 2 days and couldn't find a proper example for this one.

I have initialized the GrapeJS Editor panel as empty array to remove all the panels and have a custom panel that is provided in the example as well

For now it looks like this:
![image](https://user-images.githubusercontent.com/18398769/77723611-ef5d5f80-702b-11ea-971e-cb13d5b084c7.png)

I want the style manager to move below the custom panel that is in the right.

Thank you!

**Comment by christianbalderrama** [comment]
Is there a proper way via grapesjs that I just don't know or it have to be overriden via css

**Comment by christianbalderrama** [comment]
```css
.panel-top {
  padding: 0;
  width: 100%;
  display: flex;
  position: initial;
  justify-content: center;
  justify-content: space-between;
}
.panel-top-actions {
  position: initial;
}
```

```html
        <Row>
          <Col xs={10} md={10} lg={10}>
            <div id={this.state.id} ref={ref} style={{height}}>
              {children}
            </div>
          </Col>
          <Col xs={2} md={2} lg={2}>
            <div className="panel-top">
              <div className="panel-top-actions"></div>
            </div>
          </Col>
        </Row>
```
