### ISSUE TITLE
Custom asset manager on dropzone sample

### ISSUE THREAD

**Issue by blackbirdzzz** [artf/grapesjs#342]
hi artf, i saw that you got a big Asset manager modal when your using dropzone in your wiki exemple, it is possible to get the code or to know how to got the same modal in your GIF ?

**Comment by artf** [comment]
Hi @blackbirdzzz I just styled it with CSS, eg.
```css
.gjs-mdl-dialog {
 min-width: 1000px;
 ....
}
.gjs-am-assets {
  height: 500px;
}
```
