### ISSUE TITLE
BUG: setStyle

### ISSUE THREAD

**Issue by bovealexandre** [artf/grapesjs#4496]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

chrome latest version

### Reproducible demo link

none as it has way too much custom code with react and things like that

### Describe the bug

**How to reproduce the bug?**
add more styles to editor with setStyles

here is the string that I had in setStyles 
```css
.test {
  display: block;
}
.test .hide {
  display: none;
}
.btn {
  background:white;
}
.fresh {
  background: white;
}
.fresh .fresh-2 {
  border: 1px red solid;
}
```

**What is the expected behavior?**
add multiple styles to the editor

**What is the current behavior?**
add only the ones that are child so it's even stranger 

so for the moment it adds only those ones

```css
.fresh .fresh-2 {
  border: 1px red solid;
}
.test .hide {
  display: none;
}
```

If is necessary to execute some code in order to reproduce the bug, paste it here below:
no code necessary to test it juste setStyle from editor API

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
