### ISSUE TITLE
Add custom CSS rule

### ISSUE THREAD

**Issue by mtavkhelidze** [artf/grapesjs#501]
Hi!

I would like to add a CSS rule that, for instance, changes appearance of a component based on some attribute. I.e.
```css
[data-role=something] {
    background-color: red;
}
```

Is there a way of doing that programmatically? Or any other way for that matter.

Thanks,

Misha
