### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by artf** [artf/grapesjs#74]
This issue is a rough outline of some improvements/features we'd like to add to the editor.
To keep things cleaner it's better to open a new issue for any discussion about a related feature (then linked here) and use this one just for general questions/requests.
Don't hesitate to propose other stuff for the list and, of course, any kind of help is extremely welcome.
Each section is ordered by priority (discussable).

**Features**
- [ ] `Absolute/Designer mode` With this mode enabled the user should be able to move components "freely" inside the canvas (relying on `absolute` positioning)
- [ ] Add the possibility to group Blocks
- [ ] At the moment, once the Style Manager is configured it remains static, so for each selected component you will get the same set of style properties. Would be cool to set specific properties for different components
- [ ] GrapesJS uses the built-in CSS parser of the browser (to have less dependencies) but each browser has its own set of rules. It might be an option to attach custom parsers
- [ ] Custom color picker. eg. as with RTE using `editor.setCustomRte()` it might be `editor.setCustomColorPicker()`
- [ ] Custom Code Editor
- [ ] Image filters inside Style Manager

**Plugins**
- [ ] Image editor
- [ ] Template Manager, on start up shows a modal with templates (eg. by categories and with thumbnails) to choose or you can just import your own or start with a blank one.
- [ ] Alternative Code Editor

**Codebase**
- [ ] Get rid of `jquery`. The `data()` method is probably the only one which is strictly required by the editor
- [ ] Get rid of `grunt` in favor of `npm` scripts
- [ ] Get rid of `requirejs` in favor of `webpack` as a bundler
- [ ] Turn all ES5 code to ES6

**Comment by aloksharma1** [comment]
are you on gitter, also how about adding bootstrap support in the roadmap?

**Comment by artf** [comment]
> are you on gitter

not yet :)

Exactly, what do you mean by 'adding bootstrap'? If you're talking about loading external `style`s inside the template, you're already able to do so, check [this issue](https://github.com/artf/grapesjs-preset-newsletter/issues/1) for example

**Comment by aloksharma1** [comment]
i mean adding bootstrap components in drag-drop builder, for easy build up of websites.

**Comment by artf** [comment]
well, yeah, I add it to plugins

**Comment by givanz** [comment]
Hi

Congratulations, GrapeJs looks awesome, the most feature rich and cleanly coded open source online html editor by far.

There are some features that might make it even better in my option, here are some of my proposals.

Can the components tab be changed to show as a panel on the left? Most editors have properties and blocks shown at the same time for easier editing (jetstrap, http://ionic.io/products/creator etc).

When I click on a block, for example on map block (after adding it), I must click settings to see the block settings and to configure the map, I think that it would be easier for blocks to show settings by default or even better have only one tab for both settings and style and show settings first.

Can the interface colors/theme be easily changed by editting a scss/less file or something similar? to have different themes like one with white background.

Is it possible to toggle the elements grids (dashed boxes) by config or button? It looks cleaner without them and if it used mainly for editing editing blocks and not html elements (regular users without css/html knowledge) it might not be very useful.

Is it possible to have an option to limit highlighting/editing to only some elements (only blocks without html elements for example) on the page? I plan to use grapejs in an open source cms I'm developing and this option is helpful to limit editing only to blocks for users that are not familiar with html/css.

Is there any documentation/examples on how to add new blocks or change settings?

Thanks.

**Comment by artf** [comment]
Thanks @givanz for your kind words and suggestions.
About blocks, shown always on the left, could be a cool idea but not in the way how the canvas is now rendered. I'd like to keep canvas as wide as possible and with another side panel the view will be too much squashed. But this is just my opinion, you could easily move the block container wherever you want.
I definitely agree about 'Settings panel', I think an additional option could be a solution. Anyway I've not yet figured out the best/easiest way to manage the UI (panels, buttons, etc.) for devs, therefore all that part it's just a default set (but can be easily moved around with js).
No 'theme' options for the moment, but you can easily change the entire UI with few CSS changes
![change-ui](https://cloud.githubusercontent.com/assets/11614725/25641850/ae3a5e8c-2f96-11e7-8f7e-0973fec8b625.png)
```css
#gjs-rte-toolbar, .gjs-bg-main, .gjs-clm-select option, .gjs-clm-tags .gjs-sm-colorp-c, .gjs-editor, .gjs-mdl-dialog, .gjs-nv-item .gjs-nv-title-c, .gjs-off-prv, .gjs-pn-panel, .gjs-select option, .gjs-sm-sector .gjs-sm-colorp-c, .gjs-sm-select option, .gjs-sm-unit option, .sp-container, .gjs-block {
    background-color: white;
}
#gjs-rte-toolbar .gjs-rte-btn, .gjs-btn-prim, .gjs-btnt, .gjs-clm-tags .gjs-sm-composite.gjs-clm-field, .gjs-clm-tags .gjs-sm-field.gjs-sm-composite, .gjs-clm-tags .gjs-sm-stack #gjs-sm-add, .gjs-color-main, .gjs-mdl-dialog, .gjs-off-prv, .gjs-pn-btn, .gjs-pn-panel, .gjs-sm-sector .gjs-sm-composite.gjs-clm-field, .gjs-sm-sector .gjs-sm-field.gjs-sm-composite, .gjs-sm-sector .gjs-sm-stack #gjs-sm-add {
    color: #777;
}
.gjs-btnt.gjs-pn-active, .gjs-color-active, .gjs-pn-btn.gjs-pn-active, .gjs-pn-btn:active, .gjs-block:hover {
    color: #59a6e6;
}
.gjs-btnt.gjs-pn-active, .gjs-pn-btn.gjs-pn-active {
    background-color: rgba(0, 0, 0, 0.03);
}
```
You can already disable dashed boxes in demo
![change-switch](https://cloud.githubusercontent.com/assets/11614725/25641945/1514084c-2f97-11e7-907a-fb9f9fda0a56.png)

For creating new Blocks I suggest you check this [wiki](https://github.com/artf/grapesjs/wiki/Blocks) there you should also find how to change components properties (eg. make element not editable)
