### ISSUE TITLE
Setting background image results in duplicate style rules

### ISSUE THREAD

**Issue by TheMysticMan** [artf/grapesjs#932]
Hi @artf,

I have one strange little problem.
I have a custom trait which has an implementation for setting images and background images. 
When I set the background image a second time by using the code below I'm getting duplicated styling rules on the element Id.

```js
var style = self.target.getStyle();
// style is empty even though the stylemanager shows the default background image from the class style rule
style['background-image'] ='url("' + newUrl + '")';
self.target.setStyle(style);
```

I already played around a bit with the forceClass and avoidInlineStyle but it doesn't really help with this problem.
Maybe related to this problem: The element also has a class with a default background image. When I open the StyleManager I only see that background image in there. Not the images from the Id style rules. Looks like it doesn't really use them at all?

Thanks in advance!

**Comment by artf** [comment]
First of all, I suggest using `self.target.addStyle({'background-image': 'url(...)'})` for your case which is less verbose.
> Maybe related to this problem: The element also has a class with a default background image. When I open the StyleManager I only see that background image in there. Not the images from the Id style rules. Looks like it doesn't really use them at all?

Well if the Style Manager sees the class on the selected component you will get its styles, try to deselect the class (by using the checkbox)

**Comment by TheMysticMan** [comment]
The `addStyle` method is better indeed. It doesn't fix my problem though. 
The style manager doesn't see the styling on the id. I deselected the class checkboxes but the StyleManager also creates new rules instead of adding it to an existing rule.

```css
#ixnhha{
  background-image:url(uploads/1515695340.jpg);
  background-repeat:no-repeat;
  background-position:50% 50%;
  background-attachment:scroll;
  background-size:cover;
}
#ixnhha{
  float:left;
}
#ixnhha{
  background-image:url("uploads/1515695681.jpg");
  background-repeat-x:no-repeat;
  background-repeat-y:no-repeat;
  background-position-x:50%;
  background-position-y:50%;
  background-attachment:scroll;
  background-size:cover;
}
```
